site = "Sito di test new"
Amp = "/dev/shm/metern1.txt"
met_A = "1_2"
smtp_S = "smtp.gmail.com"
smtp_P = 587
from_addr = "email@gmail.com"
pwd = "password"
to_addrs = "mail@mail.it"
Sw_Off = 0
LowA = 4
HiA = 14
lapse = 30